source 'https://rubygems.org'

gem 'allure-cucumber'
gem 'capybara'
gem 'cucumber'
gem 'dotenv'
gem 'dotenv-rails'
gem 'erb'
gem 'factory_bot'
gem 'ffaker'
gem 'json'
gem 'logger'
gem 'pry'
gem 'rake'
gem 'require_all'
gem 'rest-client'
gem 'rspec-expectations'
gem 'rubocop', '0.63.1', require: false
gem 'selenium-webdriver'
gem 'site_prism'
gem 'typhoeus'
gem 'xpath'
gem 'yaml'
