version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  browser-tools: circleci/browser-tools@1.1.3

jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Check Chrome install
          command: |
            google-chrome --version
            chromedriver --version
#     - checkout
#      - run: bundle install
#      - run: bundle exec cucumber features/Initial.feature

workflows:
  version: 2
  build_and_test:
    jobs:
      - test


#  - run:
#      name: Which bundler?
#      command: bundle -v
#      - ruby/bundle-install


#docker:
#  - image: circleci/ruby:2.6.3-stretch-node
#  executor: ruby/default