version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  browser-tools: circleci/browser-tools@1.1.3

jobs:
#  build:
#    docker:
#      - image: circleci/ruby:2.6.3-stretch-node
#    steps:
#      - browser-tools/install-chrome
#      - browser-tools/install-chromedriver
#      - run:
#          name: Check Chrome install
#          command: |
#            google-chrome --version
#            chromedriver --version
#            bundle -v

  test:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Check Chrome install
          command: |
            google-chrome --version
            chromedriver --version
      - checkout
      - run:
          name: Install bundler and gems
          command: |
            gem install bundler:2.1.4
            bundle -v
            bundle install
      - run:
          name: Setting ENV vars and running the features
          command: |
            export DOMAIN=teladoc.io
            export CLUSTER=uat
            export SUBDOMAIN=master
            TEST_ENV=ondemand CUCUMBER_BROWSER=chrome bundle exec cucumber features/Initial.feature

workflows:
  version: 2
  test:
    jobs:
#      - build
      - test
#      - test:
#          requires:
#            - build


#  - run:
#      name: Which bundler?
#      command: bundle -v
#      - ruby/bundle-install


#docker:
#  - image: circleci/ruby:2.6.3-stretch-node
#  executor: ruby/default