version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  browser-tools: circleci/browser-tools@1.1.3

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Check Chrome install
          command: |
            google-chrome --version
            chromedriver --version
            bundle -v
            gem install bundler:2.1.4
  install_gems:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    steps:
      - checkout
      - run: bundle install
  test:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    steps:
      - checkout
      - run: TEST_ENV=ondemand CUCUMBER_BROWSER=chrome bundle exec cucumber features/Initial.feature

workflows:
  version: 2
  build_install_gems_and_test:
    jobs:
      - build
      - install_gems:
          requires:
            - build
      - test:
          requires:
            - install_gems


#  - run:
#      name: Which bundler?
#      command: bundle -v
#      - ruby/bundle-install


#docker:
#  - image: circleci/ruby:2.6.3-stretch-node
#  executor: ruby/default