default: -r features --format junit --out report/cucumber-reports/web --format pretty --color -r features -f junit --out report/cucumber-reports/failures -r features --format AllureCucumber::CucumberFormatter --out report/allure-results
